name:                bot
version:             0.1.0.0
github:              "wixe/hbot"
license:             BSD3
author:              "Wixe"
maintainer:          "wixe@ya.ru"
copyright:           "2020 Me"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/bot#readme>

dependencies:
- base                 >= 4.7 && < 5
- req                  == 3.1.*
- aeson                == 1.4.*
- http-client          == 0.6.4.*
- bytestring           == 0.10.*
- async                == 2.2.*
- text                 == 1.2.*
- time                 == 1.*
- free                 == 5.1.*
- unordered-containers == 0.2.*
- stm                  == 2.5.*
- hashable             == 1.3.*
- yaml                 == 0.11.*
- parsec               == 3.1.*
- mtl                  == 2.2.*

library:
  source-dirs: src

executables:
  bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bot
      #    - req
      #    - aeson
      #    - http-client
      #    - split
      #    - bytestring

tests:
  bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bot
