name:                bot
version:             0.1.0.0
github:              "wixe/vktgbot.hs"
license:             BSD3
author:              "Wixe"
maintainer:          "wixe@ya.ru"
copyright:           "2020 Me"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/wixe/vktgbot.hs#readme>

dependencies:
- base                 >= 4.7 && < 5
- aeson                == 1.4.*
- async                == 2.2.*
- bytestring           == 0.10.*
- free                 == 5.1.*
- hashable             == 1.3.*
- http-client          == 0.6.4.*
- http-client-tls      == 0.3.5.*
- http-types           == 0.12.*
- mtl                  == 2.2.*
- random               == 1.*
- parsec               == 3.1.*
- text                 == 1.2.*
- time                 == 1.*
- unordered-containers == 0.2.*
- uri-encode           == 1.5.*
- QuickCheck           == 2.*

library:
  source-dirs: src

executables:
  bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bot

tests:
  bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bot
